default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root

development:
  <<: *default
  database: identity_provider_development
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>
  password: <%= ENV.fetch("DB_PASSWORD", '') %>

test:
  <<: *default
  database: identity_provider_test
  host: <%= ENV['DB_HOST'] %>
  password: <%= ENV.fetch("DB_PASSWORD") %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
